# Generated by Django 2.0 on 2018-02-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='国')),
                ('province', models.CharField(blank=True, default='', max_length=255, verbose_name='省')),
                ('city', models.CharField(blank=True, default='', max_length=255, verbose_name='市')),
                ('count', models.IntegerField(default=0, verbose_name='节点数')),
                ('longitude', models.FloatField(blank=True, default=None, help_text='若保存时为空将自动从网络查询并填写', null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, default=None, help_text='若保存时为空将自动从网络查询并填写', null=True, verbose_name='纬度')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
            ],
            options={
                'verbose_name': '节点数据',
                'verbose_name_plural': '节点数据',
            },
        ),
        migrations.CreateModel(
            name='PeerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(help_text='远端节点的IP地址', max_length=15, unique=True, verbose_name='远端地址')),
                ('lastsend', models.IntegerField(help_text='最后一次成功发送数据到这个节点TCP socket的Unix epoch时间', verbose_name='最后发送时间')),
                ('lastrecv', models.IntegerField(help_text='最后一次从这个节点接收数据的Unix epoch时间', verbose_name='最后接收时间')),
                ('conntime', models.IntegerField(help_text='连接到这个节点时的Unix epoch时间', verbose_name='连接时间')),
                ('timeoffset', models.IntegerField(help_text='以秒为单位的时间偏移', verbose_name='时间偏移')),
                ('pingtime', models.FloatField(help_text='该节点最后一次响应我们的P2P ping消息的秒数', verbose_name='Ping时间')),
                ('minping', models.FloatField(blank=True, default=None, help_text='观测到的最短Ping时间（如果有的话）', null=True, verbose_name='最短Ping时间')),
                ('version', models.IntegerField(help_text='该节点使用的协议版本号', verbose_name='版本号')),
                ('subver', models.CharField(help_text='该节点在它的version消息中发送的用户代理', max_length=255, verbose_name='子版本号')),
                ('inbound', models.BooleanField(help_text='如果该节点连接到我们，设为True；如果我们连接到这个节点，设为False', verbose_name='入站')),
                ('startingheight', models.IntegerField(help_text='当它连接到我们时，在其version消息中报告的远端节点的区块链高度', verbose_name='起始高度')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('nodedata', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='node.NodeData', verbose_name='节点数据')),
            ],
            options={
                'verbose_name': '端点信息',
                'verbose_name_plural': '端点信息',
            },
        ),
        migrations.AlterUniqueTogether(
            name='nodedata',
            unique_together={('country', 'province', 'city')},
        ),
    ]
